version: '3'
services:
  postgres-slicy:
    image: postgres
    container_name: postgres-slicy
    ports:
      - "4000:5432"
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql-docker/data
    restart: always

  redis-slicy:
    image: redis
    container_name: redis-slicy
    ports:
      - '6000:6379'
    volumes:
      - ./cache-data:/data
    restart: always