"""Edited fields in the Link model

Revision ID: 00815b6b7177
Revises: 8a8852dc1ced
Create Date: 2020-05-04 02:58:39.889752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00815b6b7177'
down_revision = '8a8852dc1ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_links_short_url', table_name='links')
    op.create_index(op.f('ix_links_short_url'), 'links', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_short_url'), table_name='links')
    op.create_index('ix_links_short_url', 'links', ['short_url'], unique=False)
    # ### end Alembic commands ###
