"""Added a new method for Link model

Revision ID: 8a8852dc1ced
Revises: e3dd092af8db
Create Date: 2020-05-04 01:34:11.106372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8852dc1ced'
down_revision = 'e3dd092af8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('count_of_visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'count_of_visits')
    # ### end Alembic commands ###
